GET_PROJECTS = '''
SELECT ID,
GUID,
NAME,
GOAL,
DESCRIPTION,
NOTE,
HIGHLIGHTS,
RISKS,
PRODUCT_OWNER
FROM PROJECT WHERE ARCHIVED = 0
'''

GET_PROJECT_HISTORY = '''
SELECT ID,
GUID,
NAME,
GOAL,
DESCRIPTION,
NOTE,
HIGHLIGHTS,
RISKS,
PRODUCT_OWNER,
ACTION,
DATE_OCCURED,
USERNAME
FROM PROJECT_HISTORY WHERE GUID = '{}'
'''

GET_ALL_PROJECTS = '''
SELECT ID,
GUID,
NAME,
GOAL,
DESCRIPTION,
NOTE,
HIGHLIGHTS,
RISKS,
PRODUCT_OWNER
FROM PROJECT
'''

GET_ARCHIVED_PROJECTS = '''
SELECT ID,
GUID,
NAME,
GOAL,
DESCRIPTION,
NOTE,
HIGHLIGHTS,
RISKS,
PRODUCT_OWNER
FROM PROJECT WHERE ARCHIVED = 1
'''

GET_PROJECT_BY_ID = '''
SELECT ID,
GUID,
NAME,
GOAL,
DESCRIPTION,
NOTE,
HIGHLIGHTS,
RISKS,
PRODUCT_OWNER
FROM PROJECT
WHERE GUID = '{}'
'''

SAVE_PROJECT = '''
INSERT INTO PROJECT (ID, NAME, GOAL, NOTE, DESCRIPTION, HIGHLIGHTS, RISKS, PRODUCT_OWNER)
VALUES ('{0}','{1}','{2}','{3}','{4}','{5}','{6}','{7}')
ON DUPLICATE KEY UPDATE
NAME = '{1}',
GOAL = '{2}',
NOTE = '{3}',
DESCRIPTION = '{4}',
HIGHLIGHTS = '{5}',
RISKS = '{6}',
PRODUCT_OWNER = '{7}'
'''

GET_PROJECT_ID = '''
SELECT ID FROM PROJECT WHERE NAME = '{}'
'''

CLEAN_PROJECTS = '''
DELETE FROM PROJECT WHERE ID NOT IN({})
'''

GET_MILESTONES = '''
SELECT ID,
GUID,
PROJECT_ID,
PROJECT_GUID,
MILESTONE,
STATUS,
START_DATE,
END_DATE,
COMPLETION_DATE,
DELIVERABLE,
CURRENT_STATUS,
NEXT_STEPS,
RESOURCES,
PERCENT_COMPLETE
FROM MILESTONE WHERE ARCHIVED = 0
'''

GET_ALL_MILESTONES = '''
SELECT ID,
GUID,
PROJECT_ID,
PROJECT_GUID,
MILESTONE,
STATUS,
START_DATE,
END_DATE,
COMPLETION_DATE,
DELIVERABLE,
CURRENT_STATUS,
NEXT_STEPS,
RESOURCES,
PERCENT_COMPLETE
'''

GET_ARCHIVED_MILESTONES = '''
SELECT ID,
GUID,
PROJECT_ID,
PROJECT_GUID,
MILESTONE,
STATUS,
START_DATE,
END_DATE,
COMPLETION_DATE,
DELIVERABLE,
CURRENT_STATUS,
NEXT_STEPS,
RESOURCES,
PERCENT_COMPLETE
FROM MILESTONE WHERE ARCHIVED = 1
'''

GET_MILESTONE_BY_ID = '''
SELECT ID,
GUID,
PROJECT_ID,
PROJECT_GUID,
MILESTONE,
STATUS,
START_DATE,
END_DATE,
COMPLETION_DATE,
DELIVERABLE,
CURRENT_STATUS,
NEXT_STEPS,
RESOURCES,
PERCENT_COMPLETE
FROM MILESTONE
WHERE GUID = '{}'
'''

GET_MILESTONE_HISTORY = '''
SELECT ID,
GUID,
PROJECT_ID,
PROJECT_GUID,
MILESTONE,
STATUS,
START_DATE,
END_DATE,
COMPLETION_DATE,
DELIVERABLE,
CURRENT_STATUS,
NEXT_STEPS,
RESOURCES,
PERCENT_COMPLETE,
ACTION,
DATE_OCCURED,
USERNAME
FROM MILESTONE_HISTORY WHERE GUID = '{}'
'''

SAVE_MILESTONE = '''
INSERT INTO MILESTONE (ID, PROJECT_ID, MILESTONE, STATUS, START_DATE, END_DATE,COMPLETION_DATE, DELIVERABLE, CURRENT_STATUS, NEXT_STEPS,
RESOURCES, PERCENT_COMPLETE)
VALUES ('{0}','{1}','{2}','{3}','{4}','{5}',{6},'{7}','{8}','{9}','{10}',{11})
ON DUPLICATE KEY UPDATE
PROJECT_ID = '{1}',
MILESTONE = '{2}',
STATUS = '{3}',
START_DATE = '{4}',
END_DATE = '{5}',
COMPLETION_DATE = {6},
DELIVERABLE = '{7}',
CURRENT_STATUS = '{8}',
NEXT_STEPS = '{9}',
RESOURCES = '{10}',
PERCENT_COMPLETE = {11}
'''

GET_MILESTONE_ID = '''
SELECT ID FROM MILESTONE WHERE MILESTONE = '{}'
'''

GET_PROJECT_MILESTONES_IDS = '''
SELECT GUID FROM MILESTONE WHERE PROJECT_GUID = '{}'
AND ARCHIVED = 0
'''

GET_PROJECT_ALL_MILESTONES_IDS = '''
SELECT GUID FROM MILESTONE WHERE PROJECT_GUID = '{}'
'''

GET_COMPLETED_PROJECT_IDS = '''
SELECT DISTINCT(PROJECT_ID) FROM MILESTONE WHERE STATUS = 'Complete'
'''

CLEAN_MILESTONES = '''
DELETE FROM MILESTONE WHERE ID NOT IN({}) AND STATUS != 'Complete'
'''

GET_USER = '''
SELECT
  NETID,
  NAME,
  EMAIL
FROM USERS
WHERE NETID = '{}'
'''
