CREATE DATABASE IF NOT EXISTS `WIDGET_SHOP`;
USE `WIDGET_SHOP`;
DROP TABLE IF EXISTS `WIDGET_ORDER`;

CREATE TABLE `WIDGET_ORDER` (
    `ID` VARCHAR (36) NOT NULL,
    `TYPE` ENUM('Widget','Widget Pro','Widget Xtreme') NOT NULL,
    `COLOR` ENUM('red','blue','yellow') NOT NULL,
    `QUANTITY` INT(11) DEFAULT NULL,
    `DATE_NEEDED_BY` DATE DEFAULT NULL,
    `DATE_CREATED` DATETIME(6) NOT NULL DEFAULT NOW(6),
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DELIMITER //
CREATE TRIGGER `BEFORE_INSERT_WIDGET_ORDER`
BEFORE INSERT ON `WIDGET_ORDER`
FOR EACH ROW BEGIN
    SET NEW.`DATE_CREATED` = NOW(6);
END //
